name: Cypress tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Valid Login
        uses: cypress-io/github-action@v6

      - name: Invalid Login
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_host: https://saucedemo.com/
          CYPRESS_port: 5001

      - name: Run build and start
        env:
          CYPRESS_host: https://saucedemo.com/
          CYPRESS_port: 5001
        run: |
          npm run build
          npm start






























