name: Cypress tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Valid Login
        uses: cypress-io/github-action@v6

      - name: Invalid Login
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_host: https://saucedemo.com/
          CYPRESS_port: 5001

      - name: Check Out
        uses: actions/checkout@v4
        env:
          CYPRESS_host: https://saucedemo.com/
          CYPRESS_port: 5001
        with:
          build: npm run build
          start: npm start
          browser: chrome














